apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: pclhebtsj-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/pclhebtsj-java-quarkus-gitops